name: YAML Linting

on: pull_request

jobs:
  lint-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
